# Generated by Django 5.0.2 on 2024-02-27 11:58

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cloud', models.CharField(blank=True, choices=[('digitalocean', 'Digitalocean'), ('linode', 'Linode'), ('aws', 'AWS')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AWS',
            fields=[
                ('cloudprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.cloudprovider')),
                ('access_key', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('secret_key', fernet_fields.fields.EncryptedCharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('providers.cloudprovider',),
        ),
        migrations.CreateModel(
            name='Digitalocean',
            fields=[
                ('cloudprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.cloudprovider')),
                ('api_key', fernet_fields.fields.EncryptedCharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('providers.cloudprovider',),
        ),
        migrations.CreateModel(
            name='Linode',
            fields=[
                ('cloudprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='providers.cloudprovider')),
                ('token', fernet_fields.fields.EncryptedCharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('providers.cloudprovider',),
        ),
    ]
